INSERT INTO books values ("A-2", "奥默与海豚", "沙尔达 奥兹坎", "湖南文艺出版社", "在架可借");
INSERT INTO books values ("A-3", "暗时间", "刘未鹏", "电子工业出版社", "在架可借");
INSERT INTO books values ("A-4", "爱的五种语言", "查普曼", "江西人民出版社", "在架可借");
INSERT INTO books values ("B-9", "别相信任何人", "【英】S. J. 沃森 著", "中信出版社", "在架可借");
INSERT INTO books values ("B-10", "不抱怨的世界", "(美)威尔·鲍温", "陕西师范大学出版社", "在架可借");
INSERT INTO books values ("B-11", "冰与火之歌卷一：权力的游戏", "乔治R.R马丁 著", "重庆出版社", "在架可借");
INSERT INTO books values ("B-12", "边城", "沈从文", "长江文艺出版社", "在架可借");
INSERT INTO books values ("B-13", "白门柳", "刘斯奋", "河南文艺出版社", "在架可借");
INSERT INTO books values ("B-14", "本能：突破瓶颈，改变命运", "贝尔·格里尔斯", "同心出版社", "在架可借");
INSERT INTO books values ("B-15", "标竿人生", "（美）华理克", "上海三联书店", "在架可借");
INSERT INTO books values ("B-16", "把你的英语用起来！副标题: 原地复活你放下多年的英语", "伍君仪 / 刘晓光", "外文出版社", "在架可借");
INSERT INTO books values ("B-17", "把时间当作朋友——运用心智获得解放", "李笑来", "电子工业出版社", "在架可借");
INSERT INTO books values ("B-18", "碧山01", "左靖", "金城出版社", "在架可借");
INSERT INTO books values ("B-19", "碧山02", "左靖", "金城出版社", "在架可借");
INSERT INTO books values ("C-17", "重遇未知的自己：爱上生命中的不完美", "张德芬", "湖南文艺出版社", "在架可借");
INSERT INTO books values ("C-18", "禅与摩托车维修艺术", "罗伯特·M.波西格 (Robert M.Pirsig) ", "重庆出版社", "在架可借");
INSERT INTO books values ("C-19", "从一到无穷大", "G·伽莫夫", "科学出版社", "在架可借");
INSERT INTO books values ("C-20", "次第花开", "希阿荣博堪布", "海南出版社", "在架可借");
INSERT INTO books values ("C-21", "畅游日本", "佰程旅行网《畅游日本》编委会", "中国轻工业出版社", "在架可借");
INSERT INTO books values ("D-14", "大设计", "（英）斯蒂芬·霍金，（英）列纳德·蒙洛迪诺", "湖南科技出版社", "在架可借");
INSERT INTO books values ("D-15", "单反摄影宝典", "雷依里，郑毅", "水利水电出版社", "在架可借");
INSERT INTO books values ("D-16", "大漠谣·新版", "桐华", "湖南文艺出版社", "在架可借");
INSERT INTO books values ("D-17", "断层线（Fault Lines）", "拉古拉迈 拉詹", "中信出版社", "在架可借");
INSERT INTO books values ("D-18", "大而不倒（Too Big to Fall）", "Andrew Ross Sorkin", "Viking Adult", "在架可借");
INSERT INTO books values ("D-19", "岛", "（英）希斯洛普", "南海出版社", "在架可借");
INSERT INTO books values ("D-20", "单车上路", "刘文", "华文出版社", "在架可借");
INSERT INTO books values ("D-21", "单车囧途-丹尼的15000公里骑行历险记", "丹尼.本特", "龙门书局", "在架可借");
INSERT INTO books values ("D-22", "动物绘 38种可爱动物的色铅笔图绘", "飞乐鸟", "水利水电出版社", "在架可借");
INSERT INTO books values ("D-23", "大数据时代", "（英）迈尔-舍恩伯格", "浙江人民出版社", "在架可借");
INSERT INTO books values ("D-24", "大数据挖掘套装", "【美】Anand Rajaraman，Jeffrey D. Ullman", "人民邮电出版社", "在架可借");
INSERT INTO books values ("D-25", "独自之旅", "莱奥•罗格塞斯", "新世界出版社", "在架可借");
INSERT INTO books values ("D-26", "东南亚旅游let's go", "东南亚旅游let’s go 编辑部", "广西师范大学出版社", "在架可借");
INSERT INTO books values ("D-27", "第七天", "余华", "新星出版社", "在架可借");
INSERT INTO books values ("D-28", "小脚大脚一起走：带着孩子去旅行", "万之逸", "机械工业出版社", "在架可借");
INSERT INTO books values ("E-1", "Excel函数活用范例大辞典", "何先军", "中国铁道出版社", "在架可借");
INSERT INTO books values ("E-2", "二月河文集-康熙大帝", "二月河", "长江文艺出版社", "在架可借");
INSERT INTO books values ("E-3", "二月河文集-雍正大帝", "二月河", "长江文艺出版社", "在架可借");
INSERT INTO books values ("E-4", "二月河文集-乾隆大帝", "二月河", "长江文艺出版社", "在架可借");
INSERT INTO books values ("F-2", "福尔摩斯探案全集（上、中、下）", "柯南道尔", "天津教育出版社", "在架可借");
INSERT INTO books values ("F-3", "蜂蜜绿茶", "John Ho", "生活.读书.新知三联书店", "在架可借");
INSERT INTO books values ("F-4", "分开旅行", "陶立夏 ", "北京联合出版公司", "在架可借");
INSERT INTO books values ("F-5", "番茄工作法图解：简单易行的时间管理方法", "[瑞典] Staffan Nöteberg", "人民邮电出版社", "在架可借");
INSERT INTO books values ("F-6", "飞行骑——笨鸡走川藏", "作 者：笨鸡", "出版社: 吉林出版集团", "在架可借");
INSERT INTO books values ("G-10", "过得刚好", "郭德纲", "北京联合出版公司", "在架可借");
INSERT INTO books values ("H-9", "霍金传", "霍金", "湖南科技出版社", "在架可借");
INSERT INTO books values ("H-10", "好妈妈胜过好老师", "尹建莉", "作家出版社", "在架可借");
INSERT INTO books values ("H-11", "胡兰成经典作品集-今生今世", "胡兰成", "中国长安出版社", "在架可借");
INSERT INTO books values ("H-12", "胡兰成经典作品集-山河岁月", "胡兰成", "中国长安出版社", "在架可借");
INSERT INTO books values ("H-13", "胡兰成经典作品集-禅是一支花", "胡兰成", "中国长安出版社", "在架可借");
INSERT INTO books values ("H-14", "花之绘 38种花的色铅笔图绘(花的色铅笔绘物语，让美丽在指尖绽放)", "飞乐鸟", "水利水电出版社", "在架可借");
INSERT INTO books values ("H-15", "回忆录四部曲之一：昨天的云", "王鼎钧", "生活•读书•新知三联书店", "在架可借");
INSERT INTO books values ("H-16", "回忆录四部曲之二：怒目少年", "王鼎钧", "生活•读书•新知三联书店", "在架可借");
INSERT INTO books values ("H-17", "回忆录四部曲之三：关山夺路", "王鼎钧", "生活•读书•新知三联书店", "在架可借");
INSERT INTO books values ("H-18", "回忆录四部曲之四：文学江湖", "王鼎钧", "生活•读书•新知三联书店", "在架可借");
INSERT INTO books values ("H-19", "霍乱时期的爱情", "[哥伦比亚]加西亚·马尔克斯", "南海出版社", "在架可借");
INSERT INTO books values ("H-20", "活着", "余华", "作家出版社", "在架可借");
INSERT INTO books values ("J-23", "家庭园艺手册", "（美）贝利", "天津教育出版社", "在架可借");
INSERT INTO books values ("J-24", "九型人格", "（美）帕尔默", "华夏出版社", "在架可借");
INSERT INTO books values ("J-25", "极客与团队:软件工程师的团队生存秘笈", "菲茨帕特里克 (Brian W. Fitzpatrick) , 萨斯曼 (Ben Collins-Sussman)", "人民邮电出版社", "在架可借");
INSERT INTO books values ("J-26", "健康生活新开始", "〔美〕哈维•戴蒙德", "南海出版社", "在架可借");
INSERT INTO books values ("J-27", "柬埔寨和吴哥寺", "日本大宝石出版社　编著", "中国旅游出版社", "在架可借");
INSERT INTO books values ("J-28", "绝望锻炼了我：朴槿惠自传", "朴槿惠", "译林出版社", "在架可借");
INSERT INTO books values ("K-4", "看见", "柴静", "广西师范大学出版社", "在架可借");
INSERT INTO books values ("K-5", "苦才是人生", "索达吉堪布", "甘肃人民美术出版社", "在架可借");
INSERT INTO books values ("L-15", "伦敦塔集雨人", "斯图亚特", "上海人民出版社", "在架可借");
INSERT INTO books values ("L-16", "了不起的盖茨比", "菲兹杰拉德", "天津人民出版社", "在架可借");
INSERT INTO books values ("L-17", "历史是什么", "卡尔", "商务印书馆", "在架可借");
INSERT INTO books values ("L-18", "论中国", "（美）基辛格", "中信出版社", "在架可借");
INSERT INTO books values ("L-19", "聆听音乐", "（美）克雷格·莱特（Craig Wright）", "生活.读书.新知三联书店", "在架可借");
INSERT INTO books values ("L-20", "逻辑思维训练大全集", "余亚杰", "同心出版社", "在架可借");
INSERT INTO books values ("L-21", "狼图腾", "姜戎", "长江文艺出版社", "在架可借");
INSERT INTO books values ("M-24", "梦的解析", "（奥）西格蒙德·弗洛伊德", "国际文化出版公司", "在架可借");
INSERT INTO books values ("M-25", "梦境解析", "（美）米勒", "北京燕山出版社", "在架可借");
INSERT INTO books values ("M-26", "没有在一起，也好", "吴淡如", "现代出版社", "在架可借");
INSERT INTO books values ("M-27", "美国大萧条 [平装]", "默里·罗斯巴德(Rothbard M.N.) ", "上海人民出版社;", "在架可借");
INSERT INTO books values ("M-28", "母乳育儿全书", "威廉•西尔斯,玛莎•西尔斯,罗伯特•西尔斯,詹姆斯•西尔斯", "南海出版社", "在架可借");
INSERT INTO books values ("M-29", "美食家的字母表", "费雪", "新星出版社", "在架可借");
INSERT INTO books values ("M-30", "梦想与路径1", "梁由之", "商务印书馆", "在架可借");
INSERT INTO books values ("M-31", "梦想与路径2", "梁由之", "商务印书馆", "在架可借");
INSERT INTO books values ("M-32", "梦想与路径3", "梁由之", "商务印书馆", "在架可借");
INSERT INTO books values ("M-33", "美的历史", "翁贝托·艾柯", "中央编译出版社", "在架可借");
INSERT INTO books values ("M-34", "民主的细节", "刘瑜", "上海三联书店", "在架可借");
INSERT INTO books values ("M-35", "美国种族简史", "[美] 托马斯·索威尔", "中信出版社", "在架可借");
INSERT INTO books values ("M-36", "猫咪绘：33只萌猫的色铅笔图绘", "飞乐鸟", "水利水电出版社", "在架可借");
INSERT INTO books values ("M-37", "墨西哥旅行笔记", "徐振亚", "江西美术出版社有限责任公司", "在架可借");
INSERT INTO books values ("N-7", "挪威的森林", "村上春树", "上海译文出版社", "在架可借");
INSERT INTO books values ("N-8", "脑筋急转弯 大全集", "黄青翔　主编", "中国华侨出版社", "在架可借");
INSERT INTO books values ("N-9", "尼泊尔(Lonely Planet)", "澳大利亚LonelyPlanet公司", "中国地图出版社", "在架可借");
INSERT INTO books values ("N-10", "南渡北归（全三册)", "岳南", "湖南文艺出版社", "在架可借");
INSERT INTO books values ("O-5", "0-6岁A+育儿法", "威廉•西尔斯,玛莎•西尔斯,罗伯特•西尔斯,詹姆斯•西尔斯", "南海出版社", "在架可借");
INSERT INTO books values ("R-13", "人的行动:关于经济学的论文(套装上下册)", " 路德维希•冯•米塞斯 (作者), 余晖 (译者)", "上海人民出版社", "在架可借");
INSERT INTO books values ("R-14", "如何说孩子才会听 怎么听孩子才肯说", "（美）玛兹丽施　著，安燕玲　译", "中央编译出版社", "在架可借");
INSERT INTO books values ("S-28", "三毛典藏全集-流星雨", "三毛", "北京十月文艺出版社", "在架可借");
INSERT INTO books values ("S-29", "三毛典藏全集-雨季不再来", "三毛", "北京十月文艺出版社", "在架可借");
INSERT INTO books values ("S-30", "三毛典藏全集-撒哈拉的故事", "三毛", "北京十月文艺出版社", "在架可借");
INSERT INTO books values ("S-31", "三毛典藏全集-稻草人手记", "三毛", "北京十月文艺出版社", "在架可借");
INSERT INTO books values ("S-32", "三毛典藏全集-温柔的夜", "三毛", "北京十月文艺出版社", "在架可借");
INSERT INTO books values ("S-33", "三毛典藏全集-梦里花落知多少", "三毛", "北京十月文艺出版社", "在架可借");
INSERT INTO books values ("S-34", "三毛典藏全集-万水千山走遍", "三毛", "北京十月文艺出版社", "在架可借");
INSERT INTO books values ("S-35", "三毛典藏全集-送你一匹马", "三毛", "北京十月文艺出版社", "在架可借");
INSERT INTO books values ("S-36", "三毛典藏全集-亲爱的三毛", "三毛", "北京十月文艺出版社", "在架可借");
INSERT INTO books values ("S-37", "三毛典藏全集-我的宝贝", "三毛", "北京十月文艺出版社", "在架可借");
INSERT INTO books values ("S-38", "三毛典藏全集-滚滚红尘", "三毛", "北京十月文艺出版社", "在架可借");
INSERT INTO books values ("S-39", "上下五千年(上）", "林达汉", "文汇出版社", "在架可借");
INSERT INTO books values ("S-40", "圣经故事古希腊神话故事古罗马神话故事大全集", "博文　主编", " 华文出版社", "在架可借");
INSERT INTO books values ("S-41", "睡在悬崖上的人", "易思婷", "同心出版社", "在架可借");
INSERT INTO books values ("S-42", "史玉柱自述：我的营销心得", "史玉柱", "同心出版社", "在架可借");
INSERT INTO books values ("S-43", "生活中的经济学（第三版）", "茅于轼", "暨南大学出版社", "在架可借");
INSERT INTO books values ("S-44", "失控：全人类的最终命运和结局", "凯文·凯利 著，东西文库　译", "新星出版社", "在架可借");
INSERT INTO books values ("S-45", "30岁前的每一天", "水湄物语", "中国商业出版社", "在架可借");
INSERT INTO books values ("S-46", "思考的艺术(原书第10版)", "文森特.赖安.拉吉罗(Vincent Ryan Ruggiero)", "机械工业出版社", "在架可借");
INSERT INTO books values ("S-47", "圣经的故事", "[美]亨德里克•威廉•房龙", "武汉出版社", "在架可借");
INSERT INTO books values ("S-48", "Solaris操作系统原理", "陈向群 等编著", "机械工业出版社", "在架可借");
INSERT INTO books values ("S-49", "宋词三百首详注", "李华 编著", "百花洲文艺出版社", "在架可借");
INSERT INTO books values ("S-50", "三国演义（共两册）", "罗贯中", "人民文学出版社", "在架可借");
INSERT INTO books values ("S-51", "隋唐英雄志", "梅毅", "江西人民出版社", "在架可借");
INSERT INTO books values ("S-52", "上下五千年（下）", "林汉达", "少年儿童出版社", "在架可借");
INSERT INTO books values ("S-53", "世界国家地理地图", "《世界国家地理地图》编委会", "中国大百科全书出版社", "在架可借");
INSERT INTO books values ("T-5", "偷影子的人", "[法] 马克·李维", "湖南文艺出版社", "在架可借");
INSERT INTO books values ("T-6", "天路历程", "无", "无", "在架可借");
INSERT INTO books values ("T-7", "The Lord of the Rings 3 Volume Box Set", "约翰·罗纳德·瑞尔·托尔金", "HarperCollins UK", "在架可借");
INSERT INTO books values ("T-8", "The Hobbit", "约翰·罗纳德·瑞尔·托尔金", "HarperCollins UK", "在架可借");
INSERT INTO books values ("T-9", "天堂的证据", "【美】埃本•亚历山大 著 ", "百花洲文艺出版社 ", "在架可借");
INSERT INTO books values ("T-10", "泰国攻略", "《全球攻略》编写组", "中国旅游出版社", "在架可借");
INSERT INTO books values ("T-11", "听园（晚明传奇中的园林印象）", "肖伊绯 著", "金城出版社", "在架可借");
INSERT INTO books values ("W-12", "万物简史（彩图珍藏版)", "（美）布莱森", "接力出版社", "在架可借");
INSERT INTO books values ("W-13", "王小波时代四部曲-青铜时代", "王小波", "陕西师范大学出版社", "在架可借");
INSERT INTO books values ("W-14", "王小波时代四部曲-白银时代", "王小波", "陕西师范大学出版社", "在架可借");
INSERT INTO books values ("W-15", "王小波时代四部曲-黄金时代", "王小波", "陕西师范大学出版社", "在架可借");
INSERT INTO books values ("W-16", "王小波时代四部曲-黑铁时代", "王小波", "陕西师范大学出版社", "在架可借");
INSERT INTO books values ("W-17", "吴敬琏传—一个中国经济学家的肖像", "吴晓波", "中信出版社", "在架可借");
INSERT INTO books values ("W-18", "为什么读经典", "伊塔罗·卡尔维诺", "译林出版社", "在架可借");
INSERT INTO books values ("W-19", "乌合之众 ", "(法)古斯塔夫.勒庞", "中央编译出版社", "在架可借");
INSERT INTO books values ("W-20", "我最想要的化妆书1", "（韩）边惠玉", "广西科学技术出版社", "在架可借");
INSERT INTO books values ("W-21", "我最想要的化妆书2", "（韩）边惠玉", "广西科学技术出版社", "在架可借");
INSERT INTO books values ("X-13", "行为心理学", "龙春华　著", "中国华侨出版社", "在架可借");
INSERT INTO books values ("X-14", "西尔斯亲密育儿百科", "威廉•西尔斯,玛莎•西尔斯,罗伯特•西尔斯,詹姆斯•西尔斯", "南海出版社", "在架可借");
INSERT INTO books values ("X-15", "湘行散记", "沈从文", "长江文艺出版社", "在架可借");
INSERT INTO books values ("X-16", "小逻辑", "黑格尔", "商务印书馆", "在架可借");
INSERT INTO books values ("X-17", "西藏生死书", "索甲仁波切", "浙江大学出版社", "在架可借");
INSERT INTO books values ("X-18", "西方美术简史", "[美]亨德里克•威廉•房龙", "吉林文史出版社", "在架可借");
INSERT INTO books values ("X-19", "写给大家的中国美术史", "蒋勋", "湖南美术出版社", "在架可借");
INSERT INTO books values ("X-20", "像艺术家一样思考", "贝蒂", "北方文艺出版社", "在架可借");
INSERT INTO books values ("X-21", "小王子", "（法）圣艾修伯里", "外文出版社", "在架可借");
INSERT INTO books values ("X-22", "兄弟", "余华", "作家出版社", "在架可借");
INSERT INTO books values ("Y-11", "一学就会！70道最经典的法国甜点", "(法）梅斯", "漓江出版社", "在架可借");
INSERT INTO books values ("Y-12", "演说之禅：职场必知的幻灯片秘技", "雷纳德 ，|b|Reynolds", "电子工业出版社", "在架可借");
INSERT INTO books values ("Y-13", "越南", "（英）詹姆斯·沙利文　著，（英）克里斯 摄，马艳玲　译", "旅游教育出版社", "在架可借");
INSERT INTO books values ("Y-14", "云计算安全：架构、战略、标准与运营", "温克勒　著", "机械工业出版社", "在架可借");
INSERT INTO books values ("Y-15", "云计算与分布式系统：从并行处理到物联网", "（美）黄铠，（美）福克斯，（美）唐加拉", "机械工业出版社", "在架可借");
INSERT INTO books values ("Z-38", "这个历史挺靠谱·全三册", "袁腾飞", "武汉出版社", "在架可借");
INSERT INTO books values ("Z-39", "只有医生知道", "张羽　著", "江苏人民出版社", "在架可借");
INSERT INTO books values ("Z-40", "在厨房遇见MASA", "MASA", "河南科学技术出版社", "在架可借");
INSERT INTO books values ("Z-41", "再不远行，就老了", "王泓人", "中国华侨出版社", "在架可借");
INSERT INTO books values ("Z-42", "走吧，张小砚", "张小砚", "文化艺术出版社", "在架可借");
INSERT INTO books values ("Z-43", "中国人的焦虑从哪里来—论财富与地位的不平等", "茅于轼", "群言出版社", "在架可借");
INSERT INTO books values ("Z-44", "自然的魔法", "理查德•道金斯", "湖南科学技术出版社", "在架可借");
INSERT INTO books values ("Z-45", "中国人史纲（套装上下册）", "柏杨", "人民文学出版社", "在架可借");
INSERT INTO books values ("Z-46", "植物绘：38种梦幻植物的色铅笔图绘", "飞乐鸟　著", "水利水电出版社", "在架可借");
INSERT INTO books values ("Z-47", "中国哲学简史", "冯友兰", "北京大学出版社", "在架可借");
INSERT INTO books values ("Z-48", "正能量2：幸运的方法", "（英）理查德·怀斯曼", "湖南文艺出版社", "在架可借");
INSERT INTO books values ("Z-49", "最好的时光在路上", "郭子鹰", "中国大百科全书出版社", "在架可借");
INSERT INTO books values ("Z-50", "自在台湾", "陈斌华 著", "中国大百科全书出版社", "在架可借");
INSERT INTO books values ("Z-51", "中国地图、世界地图", "邸香平，黄玉玲", "中国地图出版社", "在架可借");
INSERT INTO books values ("Z-52", "在痛苦的世界中尽力而为", "俞敏洪", "当代中国出版社", "在架可借");
INSERT INTO books values ("Z-53", "中国国家地理地图", "中国国家地理地图编委会", "中国大百科全书出版社", "在架可借");
INSERT INTO books values ("Z-54", "自由选择", "（美）米尔顿弗里德曼，（美）罗丝D.弗里德曼　著", "机械工业出版社", "在架可借");
INSERT INTO books values ("Z-55", "左手的掌纹", "余光中", "江苏文艺出版社", "在架可借");
INSERT INTO books values ("Z-56", "长大不容易", "卢勤", "长江文艺出版社", "在架可借");
